#! /usr/bin/python3

import sys

offset = 0;

if(len(sys.argv) not in [2,3]):
  print("usage:\n  line_alternation gap [offset]\n\n  gap - number of lines between returned lines\n  offset - line to start alternating from")
  exit(0)

gap = int(sys.argv[1])
if(len(sys.argv) == 3): offset = int(sys.argv[2])
  
line = 0;

while 1:
  l = sys.stdin.readline()
  if(l):
    if(not ((line + offset) % (gap+1))):
      sys.stdout.write(l);
  else: exit(0)
  line += 1
