#! /usr/bin/python

import sys

for arg in sys.argv:
    if(arg[0] != '#'): continue
    x = arg[1:]
    if(len(x) == 3): print("\x1b[48;2;%d;%d;%dm" % (int(x[0],16)*16,int(x[1],16)*16,int(x[2],16)*16))
    if(len(x) == 6): print("\x1b[48;2;%d;%d;%dm" % (int(x[0:2],16),int(x[2:4],16),int(x[4:6],16)))
